semantic_grid_mapper_node:
  ros__parameters:
    resolution: 0.1
    length: 14.0
    height: 14.0
    log_odd_min: -100.0
    log_odd_max: 100.0
    frame_id: "map"
    use_sim_time: true
    input_topic: "/rgb_cloud"
    grid_map_topic: "semantic_grid_map"
    robot_height: 1.2
    max_veg_height: 0.4

    
